consolidate pull request workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -10,48 +10,48 @@ on:
     outputs:    
       PR_NUMBER:
         description: "The number of the pull request"
-        value: ${{ jobs.info.outputs.PR_NUMBER }}
+        value: ${{ jobs.build.outputs.PR_NUMBER }}
       PR_AUTHOR:
         description: "Author of pull request"
-        value: ${{ jobs.info.outputs.PR_AUTHOR }}
+        value: ${{ jobs.build.outputs.PR_AUTHOR }}
       REPO_NAME:
         description: "Name of the Repository"
-        value: ${{ jobs.info.outputs.REPO_NAME }}
+        value: ${{ jobs.build.outputs.REPO_NAME }}
       CODE_OWNER:
         description: " Owner of Repository" # assumes single owner
-        value: ${{ jobs.info.outputs.CODE_OWNER }}
+        value: ${{ jobs.build.outputs.CODE_OWNER }}
       HEAD_BRANCH:
         description: "Branch containing changes (contains work to be merged)"
-        value: ${{ jobs.info.outputs.HEAD_BRANCH }}
+        value: ${{ jobs.build.outputs.HEAD_BRANCH }}
       VERSION:
         description: "Version to  released"
-        value: ${{ jobs.info.outputs.VERSION }}
+        value: ${{ jobs.build.outputs.VERSION }}
       RELEASE_TITLE:
         description: "Title displayed in release notes and changelog"
-        value: ${{ jobs.info.outputs.RELEASE_TITLE }}
+        value: ${{ jobs.build.outputs.RELEASE_TITLE }}
       NEW_TAG:
         description: "The most recently merged tag (on the HEAD/SOURCE branch)"
-        value: ${{ jobs.info.outputs.NEW_TAG }}
+        value: ${{ jobs.build.outputs.NEW_TAG }}
       OLD_TAG:
         description: "The oldest merged tag (on the HEAD/SOURCE branch)"
-        value: ${{ jobs.info.outputs.OLD_TAG }}
+        value: ${{ jobs.build.outputs.OLD_TAG }}
       LAST_RELEASE:
         description: "Last Release Tag"
-        value: ${{ jobs.info.outputs.LAST_RELEASE }}
+        value: ${{ jobs.build.outputs.LAST_RELEASE }}
       LAST_RELEASE_PRESENT: 
         description: " Boolean; if false then its the first release"
-        value: ${{ jobs.info.outputs.LAST_RELEASE_PRESENT }}
+        value: ${{ jobs.build.outputs.LAST_RELEASE_PRESENT }}
 
 jobs:
-  info:
+  build:
     runs-on: ${{ inputs.platform }} # Use the platform input here
     if: ${{ github.event_name == 'pull_request' }}
     outputs:
       PR_NUMBER: ${{ steps.pr.outputs.number }}
       PR_AUTHOR: ${{ steps.author.outputs.author }}
+      HEAD_BRANCH: ${{ steps.branch.outputs.name }}
       REPO_NAME: ${{ steps.repo_name.outputs.repo }}
       CODE_OWNER: ${{ steps.code_owner.outputs.owner }}
-      HEAD_BRANCH: ${{ steps.branch.outputs.name }}
       VERSION: ${{ steps.version.outputs.release_version }}
       RELEASE_TITLE: ${{ steps.release_title.outputs.release_title }}
       NEW_TAG: ${{ steps.new_tag.outputs.new_tag }}
@@ -67,6 +67,19 @@ jobs:
       - name: Retrieve Tags
         run: |
           git fetch --tags
+
+      - name: Head Branch Name
+        id: branch
+        run: |
+          HEADREF="${GITHUB_HEAD_REF}"
+          echo "name=${HEADREF}" >> "$GITHUB_OUTPUT"
+
+      - name: Repository Name
+        id: repo_name
+        env:
+          GITHUB_REPOSITORY: ${{ github.repo }}
+        run: |
+          echo "repo=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
 
       - name: Pull Request Number
         id: pr
@@ -93,13 +106,6 @@ jobs:
             exit 1
           fi
 
-      - name: Repository Name
-        id: repo_name
-        env:
-          GITHUB_REPOSITORY: ${{ github.repo }}
-        run: |
-          echo "repo=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
-
       - name: Code Owner
         id: code_owner
         run: |
@@ -118,12 +124,6 @@ jobs:
             echo "first line in .github/CODEOWNERS is empty : ${FIRSTLINE}"
             exit 1
           fi
-
-      - name: Head Branch Name
-        id: branch
-        run: |
-          HEADREF="${GITHUB_HEAD_REF}"
-          echo "name=${HEADREF}" >> "$GITHUB_OUTPUT"
 
       - name: Validate Branch Name
         env:
@@ -209,3 +209,76 @@ jobs:
           else
             echo "present=false" >> "$GITHUB_OUTPUT"
           fi
+
+  assign:
+    needs: build
+    runs-on: ${{ inputs.platform }}
+    if: ${{ github.event.pull_request.state == 'open' || github.event.action == 'reopened' }}    
+    env:
+      PR_NUMBER: ${{ needs.build.outputs.PR_NUMBER }}
+      PR_AUTHOR: ${{ needs.build.outputs.PR_AUTHOR }}
+      REPO_NAME: ${{ needs.build.outputs.REPO_NAME }}
+      CODE_OWNER: ${{ needs.build.outputs.CODE_OWNER }}
+      HEAD_BRANCH: ${{ needs.build.outputs.HEAD_BRANCH }}
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check for Reviewer
+        id: check_reviewer
+        run: |
+          echo "Checking if a reviewer is already assigned to PR: $PR_NUMBER"
+
+          if [[ -n "${PR_NUMBER}" ]]; then
+            CURRENT_REVIEWERS=$(gh pr view "$PR_NUMBER" --json reviewRequests --jq '.reviewRequests | length')
+            echo "current_reviewers=$CURRENT_REVIEWERS" >> $GITHUB_ENV
+          else
+            echo "Missing required input: PR number"
+            exit 1
+          fi
+
+
+  # approval:
+  #   needs: [build, assign]
+  #   runs-on: ${{ inputs.platform }}
+  #   env:
+  #     GH_TOKEN: ${{ github.token }}
+  #     PR_NUMBER: ${{ needs.build.outputs.PR_NUMBER }}
+  #     PR_AUTHOR: ${{ needs.build.outputs.PR_AUTHOR }}
+  #     REPO_NAME: ${{ needs.build.outputs.REPO_NAME }}
+  #     CODE_OWNER: ${{ needs.build.outputs.CODE_OWNER }}
+  #     HEAD_BRANCH: ${{ needs.build.outputs.HEAD_BRANCH}}
+  #   steps:
+  #     - name: Automatic
+  #       if: ${{ env.PR_AUTHOR == env.CODE_OWNER }}
+  #       uses: actions/github-script@v7
+  #       with:
+  #         script: |
+  #           const pr_number = context.payload.pull_request.number;
+
+  #           if (!pr_number) {
+  #             throw new Error("Pull request number not found in the context.");
+  #           }
+
+  #           await github.rest.pulls.createReview({
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             pull_number: pr_number,
+  #             event: 'APPROVE'
+  #           });
+
+  #     - name: Not Automatic
+  #       if: github.event_name == 'issue_comment' && github.event.action == 'created' && github.event.issue.pull_request && contains(github.event.comment.body, 'approved')
+  #       run: |
+  #         commenter=$( echo "${{ github.event.comment.user.login }}" )
+
+  #         if [[ "$CODE_OWNER" != "*$commenter*" ]]; then
+  #           echo "commenter is not a reviewer; cannot approve"
+  #           gh pr lock "$PR_NUMBER" -r "spam"
+  #           exit 1
+  #         else
+  #           gh pr review "$PR_NUMBER" --approve
+  #         fi
